### ISSUE TITLE
Add coroutine extensions to Mono and Flux

### ISSUE THREAD

**Issue by sdeleuze** [reactor/reactor-kotlin-extensions#2]
It could follow the same principle than https://github.com/gildor/kotlin-coroutines-retrofit.

**Comment by konrad-kaminski** [comment]
There's actually a pull request for this in [https://github.com/Kotlin/kotlinx.coroutines/pull/52]. The question is should these extensions be a part of [https://github.com/Kotlin/kotlinx.coroutines] or [https://github.com/reactor/reactor-kotlin-extensions] ?

**Comment by sdeleuze** [comment]
Would be nice if they include that directly in https://github.com/Kotlin/kotlinx.coroutines I think.

**Comment by sdeleuze** [comment]
Merged in kotlinx.coroutines as part of https://github.com/Kotlin/kotlinx.coroutines/pull/52 so I close this issue.
