### ISSUE TITLE
Problem when using switchIfEmpty on a Flux (vol.2)

### ISSUE THREAD

**Issue by MastaP** [reactor/reactor-kotlin-extensions#20]
Hi, I've stumbled upon exactly the same issue described in #10 and it's still valid.

I also checked the test @simonbasle was referring to and it turns out the test is incorrect
https://github.com/reactor/reactor-kotlin-extensions/blob/master/src/test/kotlin/reactor/kotlin/core/publisher/FluxExtensionsTests.kt#L229
First, it does not test switchIfEmpty behavior since the flux is not empty,
Second, it does NOT use switchIfEmpty extension function!
If I add a new line, it's clearly visible from the IDE:
![image](https://user-images.githubusercontent.com/185344/110925224-3585fe80-8323-11eb-9f61-80fa9549445c.png)

The following method is called coming from reactor.core.publisher.Flux:
`Flux<T> switchIfEmpty(Publisher<? extends T> alternate)`

## Expected Behavior
Be able to import and use the extension function

**Comment by simonbasle** [comment]
Looks like this extension is pretty useless, then.
Any suggestion on a possible improvement?

**Comment by MastaP** [comment]
p.s. moving `FluxExtensionsTests` file to a different package than `reactor.kotlin.core.publisher` and avoiding wildcard imports will expose more issues with `FluxExtensionsTests`

**Comment by MastaP** [comment]
`switchIfEmptyDeferred`?

**Comment by OlegDokuka** [comment]
Well, looks ugly but that is how it can be workaround now, otherwise, it creates anonymous Publisher impl 

```
.switchIfEmpty ({ throw RuntimeException("error which should not happen due to defered execution") } as (() -> Publisher<Int>))
```

**Comment by OlegDokuka** [comment]
the other possible solution is to name extension differently. I don't think we can fix it other than that. The compiler treats anonymous function as anonymous Publisher impl and we can nothing to do with that

**Comment by OlegDokuka** [comment]
> switchIfEmptyDeferred?

@MastaP yeah, that what came to my mind as well. Do you wanna create a PR for that?

**Comment by MastaP** [comment]
> Do you wanna create a PR for that?

I can. (but I will not change the package of the test class)
